swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /v1/hello:
    get:
      summary: Hi Service
      operationId: hello-v1
      x-google-backend:
        address: https://asia-south1-development-369707.cloudfunctions.net/hello_funtion
      responses:
        '200':
          description: OK
  /v1/login:
    get:
      summary: login Service
      operationId: login-v1
      x-google-backend:
        address: https://asia-south1-development-369707.cloudfunctions.net/login_funtion
      responses:
        '200':
          description: OK