swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  # /v1/hello:
  #   get:
  #     summary: Hi Service
  #     operationId: hello-v1
  #     x-google-backend:
  #       address: https://asia-south1-development-369707.cloudfunctions.net/hello_funtion
  #     responses:
  #       '200':
  #         description: OK
  /v1/user_login:
    post:
      summary: user login.
      operationId: user_login-v1
      x-google-backend:
        address: https://asia-south1-development-369707.cloudfunctions.net/user_login_function
      responses:
        '200':
          description: OK